### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by benjick** [mittwald/kube-httpcache#46]
**Describe the bug**
Pod crashes and when I check the logs the first error is this:

```
fatal error: concurrent map read and map write

goroutine 9 [running]:
runtime.throw(0x115bcf3, 0x21)
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/panic.go:1116 +0x72 fp=0xc002ec94e0 sp=0xc002ec94b0 pc=0x432f92
runtime.mapaccess1_faststr(0x1096d20, 0xc0035e9440, 0x114b2bc, 0xf, 0x11c8ce8)
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/map_faststr.go:21 +0x43c fp=0xc002ec9550 sp=0xc002ec94e0 pc=0x41277c
net/textproto.MIMEHeader.Get(0xc0035e9440, 0x114b2bc, 0xf, 0xc000001a01, 0xc002ec97c8)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/textproto/header.go:34 +0x5d fp=0xc002ec9588 sp=0xc002ec9550 pc=0x7606ed
net/http.Header.Get(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/header.go:46
net/http.(*persistConn).roundTrip(0xc003a9bb00, 0xc0035e97d0, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:2438 +0xdf2 fp=0xc002ec9898 sp=0xc002ec9588 pc=0x7f4542
net/http.(*Transport).roundTrip(0x1a5a240, 0xc003835000, 0xc0002b3880, 0xc002ec9b28, 0x40ca38)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:565 +0xad9 fp=0xc002ec9ae0 sp=0xc002ec9898 pc=0x7e8c69
net/http.(*Transport).RoundTrip(0x1a5a240, 0xc003835000, 0x1a5a240, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/roundtrip.go:17 +0x35 fp=0xc002ec9b18 sp=0xc002ec9ae0 pc=0x7cf395
net/http.send(0xc003835000, 0x12ad580, 0x1a5a240, 0x0, 0x0, 0x0, 0xc000764ed8, 0x0, 0x1, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/client.go:252 +0x43e fp=0xc002ec9c80 sp=0xc002ec9b18 pc=0x79251e
net/http.(*Client).send(0xc0003087e0, 0xc003835000, 0x0, 0x0, 0x0, 0xc000764ed8, 0x0, 0x1, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/client.go:176 +0xfa fp=0xc002ec9d00 sp=0xc002ec9c80 pc=0x791f3a
net/http.(*Client).do(0xc0003087e0, 0xc003835000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/client.go:699 +0x44a fp=0xc002ec9ed8 sp=0xc002ec9d00 pc=0x793c0a
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/client.go:567
github.com/mittwald/kube-httpcache/pkg/signaller.(*Signaller).ProcessSignalQueue(0xc00029efc0)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/signaller/run.go:59 +0xc6 fp=0xc002ec9fd8 sp=0xc002ec9ed8 pc=0xef9696
runtime.goexit()
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc002ec9fe0 sp=0xc002ec9fd8 pc=0x462b41
created by github.com/mittwald/kube-httpcache/pkg/signaller.(*Signaller).Run
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/signaller/run.go:21 +0x11c

goroutine 1 [chan receive, 347 minutes]:
github.com/mittwald/kube-httpcache/pkg/controller.(*VarnishController).Run(0xc00012e2a0, 0x12d7240, 0xc00028f5c0, 0xc00029d710, 0xc00029d710)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/controller/run.go:58 +0x39d
main.main()
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:147 +0x562

goroutine 18 [chan receive, 2 minutes]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1a644c0)
	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f

goroutine 19 [chan receive, 45 minutes]:
github.com/mittwald/kube-httpcache/pkg/watcher.(*EndpointWatcher).watch(0xc000285a40, 0xc000102360, 0xc0001023c0)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/watcher/endpoints_watch.go:37 +0x375
created by github.com/mittwald/kube-httpcache/pkg/watcher.(*EndpointWatcher).Run
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/watcher/endpoints_watch.go:17 +0x98

goroutine 20 [chan receive, 34 minutes]:
github.com/mittwald/kube-httpcache/pkg/watcher.(*EndpointWatcher).watch(0xc000285a90, 0xc000102420, 0xc000102480)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/watcher/endpoints_watch.go:37 +0x375
created by github.com/mittwald/kube-httpcache/pkg/watcher.(*EndpointWatcher).Run
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/watcher/endpoints_watch.go:17 +0x98

goroutine 21 [syscall, 347 minutes]:
syscall.Syscall6(0xe8, 0x7, 0xc00040fb74, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/syscall/asm_linux_amd64.s:41 +0x5
golang.org/x/sys/unix.EpollWait(0x7, 0xc00040fb74, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/golang.org/x/sys@v0.0.0-20181011152604-fa43e7bc11ba/unix/zsyscall_linux_amd64.go:1641 +0x72
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0001338c0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/inotify_poller.go:86 +0x91
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000285ae0)
	/home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/inotify.go:192 +0x1f8
created by github.com/fsnotify/fsnotify.NewWatcher
	/home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/inotify.go:59 +0x1a5

goroutine 22 [chan receive, 347 minutes]:
github.com/mittwald/kube-httpcache/pkg/watcher.(*fsnotifyTemplateWatcher).watch(0xc0002be8a0, 0xc000102660, 0xc0001026c0)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/watcher/template_watch.go:18 +0x76
created by github.com/mittwald/kube-httpcache/pkg/watcher.(*fsnotifyTemplateWatcher).Run
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/watcher/template_watch.go:12 +0x98

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x7f4127306d28, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00030c698, 0x72, 0x0, 0x0, 0x1145bf1)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00030c680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00030c680, 0xa7e873307a7c1c8b, 0x0, 0xa7e873307a7c1c8b)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000c480, 0x5fbde082, 0xc00010ed90, 0x487636)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000c480, 0xc00010ede0, 0x18, 0xc000270f00, 0x7db84c)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc00003a0e0, 0x12d5040, 0xc00000c480, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2930 +0x25d
net/http.(*Server).ListenAndServe(0xc00003a0e0, 0x11c7ca0, 0xc00029efc0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2859 +0xb7
github.com/mittwald/kube-httpcache/pkg/signaller.(*Signaller).Run(0xc00029efc0, 0x0, 0x0)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/signaller/run.go:24 +0x13e
main.main.func1(0xc00029efc0, 0xc000279f30)
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:93 +0x2b
created by main.main
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:92 +0x792

goroutine 24 [select, 347 minutes]:
main.main.func2(0xc0001023c0, 0xc000102480, 0xc0001026c0, 0xc000102780)
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:102 +0x145
created by main.main
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:100 +0x2c7

goroutine 26 [syscall, 347 minutes]:
os/signal.signal_recv(0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/signal/signal.go:127 +0x44

goroutine 6264 [select, 288 minutes]:
net/http.(*persistConn).readLoop(0xc001579440)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:2099 +0x99e
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1647 +0xc56

goroutine 71 [select, 213 minutes]:
github.com/mittwald/kube-httpcache/pkg/controller.(*VarnishController).watchConfigUpdates(0xc00012e2a0, 0x12d7240, 0xc00028f5c0, 0xc00026e6e0, 0xc000044300)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/controller/watch.go:20 +0x199
created by github.com/mittwald/kube-httpcache/pkg/controller.(*VarnishController).Run
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/controller/run.go:48 +0x355

goroutine 69 [select, 347 minutes]:
net/http.(*persistConn).writeLoop(0xc0001ef200)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1648 +0xc7b

goroutine 33 [chan receive, 347 minutes]:
main.main.func3(0xc0002da540, 0xc00029d710)
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:141 +0x41
created by main.main
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:140 +0x537

goroutine 30 [IO wait, 34 minutes]:
internal/poll.runtime_pollWait(0x7f4127306e08, 0x72, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00030c618, 0x72, 0x3800, 0x38b1, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00030c600, 0xc00049a000, 0x38b1, 0x38b1, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00030c600, 0xc00049a000, 0x38b1, 0x38b1, 0x203000, 0x7f414dfddd30, 0xc8)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e050, 0xc00049a000, 0x38b1, 0x38b1, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000561900, 0xc00049a000, 0x38b1, 0x38b1, 0x66b, 0x38ac, 0xc0004a19c8)
	/opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00003d058, 0x12ac260, 0xc000561900, 0x40a115, 0x1029d60, 0x1105ec0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00003ce00, 0x12ad4c0, 0xc00000e050, 0x5, 0xc00000e050, 0x8)
	/opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00003ce00, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00003ce00, 0xc00042d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc00042a5a0, 0xc00012e498, 0x9, 0x9, 0x46c70c, 0xc000158040, 0x651)
	/opt/hostedtoolcache/go/1.14.7/x64/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x12ac120, 0xc00042a5a0, 0xc00012e498, 0x9, 0x9, 0x9, 0xc000158030, 0x11c8ce0, 0xc000158028)
	/opt/hostedtoolcache/go/1.14.7/x64/src/io/io.go:310 +0x87
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc00012e498, 0x9, 0x9, 0x12ac120, 0xc00042a5a0, 0x0, 0x0, 0xc002b2c0f0, 0x0)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20181011144130-49bb7cea24b1/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00012e460, 0xc002b2c0f0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20181011144130-49bb7cea24b1/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0004a1fa8, 0xc000060fb0, 0x7fa872)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20181011144130-49bb7cea24b1/http2/transport.go:1616 +0x8d
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000271c80)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20181011144130-49bb7cea24b1/http2/transport.go:1544 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20181011144130-49bb7cea24b1/http2/transport.go:619 +0x64a

goroutine 4443 [select, 315 minutes]:
net/http.(*persistConn).writeLoop(0xc00132f560)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1648 +0xc7b

goroutine 154 [select, 345 minutes]:
net/http.(*persistConn).writeLoop(0xc00013a5a0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1648 +0xc7b

goroutine 54 [syscall, 347 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x13, 0xc000112de0, 0x1000004, 0x0, 0x0, 0x4d2603, 0xc00042a300, 0xc000112e20)
	/opt/hostedtoolcache/go/1.14.7/x64/src/syscall/asm_linux_amd64.s:41 +0x5
os.(*Process).blockUntilWaitable(0xc0005ac990, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc0005ac990, 0x11c8880, 0x11c8888, 0x11c8878)
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc00026e6e0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/exec/exec.go:507 +0x60
os/exec.(*Cmd).Run(0xc00026e6e0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/exec/exec.go:341 +0x5c
github.com/mittwald/kube-httpcache/pkg/controller.(*VarnishController).startVarnish.func1(0xc00026e6e0, 0xc0005ae4e0)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/controller/run.go:75 +0x2b
created by github.com/mittwald/kube-httpcache/pkg/controller.(*VarnishController).startVarnish
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/controller/run.go:74 +0x149

goroutine 55 [select, 347 minutes]:
os/exec.(*Cmd).Start.func2(0xc00026e6e0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/exec/exec.go:449 +0xc4
created by os/exec.(*Cmd).Start
	/opt/hostedtoolcache/go/1.14.7/x64/src/os/exec/exec.go:448 +0x6d0

goroutine 216 [select, 347 minutes]:
net/http.(*persistConn).writeLoop(0xc0001a0c60)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1648 +0xc7b

goroutine 72 [chan receive, 213 minutes]:
github.com/mittwald/kube-httpcache/pkg/controller.(*VarnishController).Run.func1(0xc000044300)
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/controller/run.go:51 +0x41
created by github.com/mittwald/kube-httpcache/pkg/controller.(*VarnishController).Run
	/home/runner/work/kube-httpcache/kube-httpcache/pkg/controller/run.go:50 +0x377
```

Then it's about 2MB of spam and finally:

```
goroutine 15124 [IO wait]:
internal/poll.runtime_pollWait(0x7f4126fe51d0, 0x72, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc003a81198, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc003a81180, 0xc003b92000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc003a81180, 0xc003b92000, 0x1000, 0x1000, 0x10, 0x45de00, 0xc00385b380)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000764ee0, 0xc003b92000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc003a9bb00, 0xc003b92000, 0x1000, 0x1000, 0x404fad, 0x60, 0x0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc0039db2c0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc0039db2c0, 0x1, 0xc003a95380, 0x40c1c6, 0xc0039db200, 0x60, 0x60)
	/opt/hostedtoolcache/go/1.14.7/x64/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc003a9bb00)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1647 +0xc56

goroutine 15125 [runnable]:
net/http.(*persistConn).writeLoop(0xc003a9bb00)
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:2274
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/transport.go:1648 +0xc7b
```

I couldn't add the whole log but let me know if you need it and I can upload it somewhere

This locks up my whole site until i do `kubectl delete pod --force`.

**To Reproduce**
I'm not really sure why this happens. This happened first now during Black Week and with increased traffic.

**Expected behavior**
Either for this not to happen or for the process to recover from it.

**Environment:**
 - Kubernetes version: 1.17
 - kube-httpcache version: stable (how can I check exactly?)

**Configuration**
<details>
  <summary>varnish.vcl</summary>
  
```vcl
vcl 4.0;

import std;
# The minimal Varnish version is 4.0
# For SSL offloading, pass the following header in your proxy server or load balancer: 'X-Forwarded-Proto: https'

backend default {
    .host = "localhost";
    .port = "8080";
    .first_byte_timeout = 600s;
    .probe = {
        .url = "/pub/health_check.php";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }
}

acl purge {
    "localhost";
}

sub vcl_recv {
    if (req.method == "PURGE") {
        if (client.ip !~ purge) {
            return (synth(405, "Method not allowed"));
        }
        # To use the X-Pool header for purging varnish during automated deployments, make sure the X-Pool header
        # has been added to the response in your backend server config. This is used, for example, by the
        # capistrano-magento2 gem for purging old content from varnish during it's deploy routine.
        if (!req.http.X-Magento-Tags-Pattern && !req.http.X-Pool) {
            return (synth(400, "X-Magento-Tags-Pattern or X-Pool header required"));
        }
        if (req.http.X-Magento-Tags-Pattern) {
          ban("obj.http.X-Magento-Tags ~ " + req.http.X-Magento-Tags-Pattern);
        }
        if (req.http.X-Pool) {
          ban("obj.http.X-Pool ~ " + req.http.X-Pool);
        }
        return (synth(200, "Purged"));
    }

    if (req.method != "GET" &&
        req.method != "HEAD" &&
        req.method != "PUT" &&
        req.method != "POST" &&
        req.method != "TRACE" &&
        req.method != "OPTIONS" &&
        req.method != "DELETE") {
          /* Non-RFC2616 or CONNECT which is weird. */
          return (pipe);
    }

    # We only deal with GET and HEAD by default
    if (req.method != "GET" && req.method != "HEAD") {
        return (pass);
    }

    # Bypass shopping cart, checkout and search requests
    if (req.url ~ "/checkout" || req.url ~ "/catalogsearch") {
        return (pass);
    }

    # Bypass health check requests
    if (req.url ~ "/pub/health_check.php") {
        return (pass);
    }

    # Set initial grace period usage status
    set req.http.grace = "none";

    # normalize url in case of leading HTTP scheme and domain
    set req.url = regsub(req.url, "^http[s]?://", "");

    # collect all cookies
    std.collect(req.http.Cookie);

    # Compression filter. See https://www.varnish-cache.org/trac/wiki/FAQ/Compression
    if (req.http.Accept-Encoding) {
        if (req.url ~ "\.(jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {
            # No point in compressing these
            unset req.http.Accept-Encoding;
        } elsif (req.http.Accept-Encoding ~ "gzip") {
            set req.http.Accept-Encoding = "gzip";
        } elsif (req.http.Accept-Encoding ~ "deflate" && req.http.user-agent !~ "MSIE") {
            set req.http.Accept-Encoding = "deflate";
        } else {
            # unknown algorithm
            unset req.http.Accept-Encoding;
        }
    }

    # Remove Google gclid parameters to minimize the cache objects
    set req.url = regsuball(req.url,"\?gclid=[^&]+$",""); # strips when QS = "?gclid=AAA"
    set req.url = regsuball(req.url,"\?gclid=[^&]+&","?"); # strips when QS = "?gclid=AAA&foo=bar"
    set req.url = regsuball(req.url,"&gclid=[^&]+",""); # strips when QS = "?foo=bar&gclid=AAA" or QS = "?foo=bar&gclid=AAA&bar=baz"

    # Static files caching
    if (req.url ~ "^/(pub/)?(media|static)/") {
        # Static files should not be cached by default
        return (pass);

        # But if you use a few locales and don't use CDN you can enable caching static files by commenting previous line (#return (pass);) and uncommenting next 3 lines
        #unset req.http.Https;
        #unset req.http.X-Forwarded-Proto;
        #unset req.http.Cookie;
    }

    return (hash);
}

sub vcl_hash {
    if (req.http.cookie ~ "X-Magento-Vary=") {
        hash_data(regsub(req.http.cookie, "^.*?X-Magento-Vary=([^;]+);*.*$", "\1"));
    }

    # For multi site configurations to not cache each other's content
    if (req.http.host) {
        hash_data(req.http.host);
    } else {
        hash_data(server.ip);
    }

    # To make sure http users don't see ssl warning
    if (req.http.X-Forwarded-Proto) {
        hash_data(req.http.X-Forwarded-Proto);
    }
    
}

sub vcl_backend_response {

    set beresp.grace = 3d;

    if (beresp.http.content-type ~ "text") {
        set beresp.do_esi = true;
    }

    if (bereq.url ~ "\.js$" || beresp.http.content-type ~ "text") {
        set beresp.do_gzip = true;
    }

    if (beresp.http.X-Magento-Debug) {
        set beresp.http.X-Magento-Cache-Control = beresp.http.Cache-Control;
    }

    # cache only successfully responses and 404s
    if (beresp.status != 200 && beresp.status != 404) {
        set beresp.ttl = 0s;
        set beresp.uncacheable = true;
        return (deliver);
    } elsif (beresp.http.Cache-Control ~ "private") {
        set beresp.uncacheable = true;
        set beresp.ttl = 86400s;
        return (deliver);
    }

    # validate if we need to cache it and prevent from setting cookie
    if (beresp.ttl > 0s && (bereq.method == "GET" || bereq.method == "HEAD")) {
        unset beresp.http.set-cookie;
    }

   # If page is not cacheable then bypass varnish for 2 minutes as Hit-For-Pass
   if (beresp.ttl <= 0s ||
       beresp.http.Surrogate-control ~ "no-store" ||
       (!beresp.http.Surrogate-Control &&
       beresp.http.Cache-Control ~ "no-cache|no-store") ||
       beresp.http.Vary == "*") {
       # Mark as Hit-For-Pass for the next 2 minutes
        set beresp.ttl = 120s;
        set beresp.uncacheable = true;
    }

    return (deliver);
}

sub vcl_deliver {
    if (resp.http.X-Magento-Debug) {
        if (resp.http.x-varnish ~ " ") {
            set resp.http.X-Magento-Cache-Debug = "HIT";
            set resp.http.Grace = req.http.grace;
        } else {
            set resp.http.X-Magento-Cache-Debug = "MISS";
        }
    } else {
        unset resp.http.Age;
    }

    # Not letting browser to cache non-static files.
    if (resp.http.Cache-Control !~ "private" && req.url !~ "^/(pub/)?(media|static)/") {
        set resp.http.Pragma = "no-cache";
        set resp.http.Expires = "-1";
        set resp.http.Cache-Control = "no-store, no-cache, must-revalidate, max-age=0";
    }

    unset resp.http.X-Magento-Debug;
    unset resp.http.X-Magento-Tags;
    unset resp.http.X-Powered-By;
    unset resp.http.Server;
    unset resp.http.X-Varnish;
    unset resp.http.Via;
    unset resp.http.Link;
}

sub vcl_hit {
    if (obj.ttl >= 0s) {
        # Hit within TTL period
        return (deliver);
    }
    if (std.healthy(req.backend_hint)) {
        if (obj.ttl + 300s > 0s) {
            # Hit after TTL expiration, but within grace period
            set req.http.grace = "normal (healthy server)";
            return (deliver);
        } else {
            # Hit after TTL and grace expiration
            return (fetch);
        }
    } else {
        # server is not healthy, retrieve from cache
        set req.http.grace = "unlimited (unhealthy server)";
        return (deliver);
    }
}
```
</details>

StatefulSet args:
```yaml
args: [
  '-admin-addr=0.0.0.0',
  '-admin-port=6083',
  '-signaller-enable',
  '-signaller-port=8090',
  '-frontend-watch',
  '-frontend-namespace=$(NAMESPACE)',
  '-frontend-service=varnish-service',
  '-backend-watch',
  '-backend-namespace=$(NAMESPACE)',
  '-backend-service=$(BACKEND)',
  '-varnish-secret-file=/etc/varnish/k8s-secret/secret',
  '-varnish-vcl-template=/etc/varnish/tmpl/default.vcl.tmpl',
  '-varnish-storage=malloc,512M',
],
```

**Comment by martin-helmich** [comment]
Huh... From a quick glance, this looks like the panic occurrs somewhere in Go's HTTP client in the signaller component.

It seems like the signaller component multiplexes a `*http.Request` instance and passes it (once for each endpoint) into a queue:

https://github.com/mittwald/kube-httpcache/blob/a3c0873830f40600ca49c33d89a0da49107a0f6d/pkg/signaller/run.go#L40-L50

Probably, a single `*http.Request` instance is not intended to be executed multiple times concurrently. This would probably be easily fixed by cloning the `http.Request` and passing a separate copy into each goroutine.

**Comment by martin-helmich** [comment]
@benjick This should have been fixed by cloning the request headers for each goroutine in #47. That fix was released in 0.3.4 -- can you give it a try and see if it alleviates your issue? Thanks for the report, btw. :+1:

**Comment by benjick** [comment]
@martin-helmich thank you 🙏 I will try this out right away

**Comment by benjick** [comment]
It also seems the pods aren't getting stuck in `Terminating` after this update, but I'm not sure
