### ISSUE TITLE
Occasional panic when WATCH'ing

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/kube-httpcache#5]
```
panic: Get https://10.10.10.1:443/api/v1/namespaces/XXX/endpoints?fieldSelector=metadata.name%3Dproduction-app&watch=true: unexpected EOF

goroutine 19 [running]:
github.com/martin-helmich/kube-httpcache/watcher.(*BackendWatcher).watch(0xc000235c20)
	/app/watcher/types.go:59 +0xe6a
created by github.com/martin-helmich/kube-httpcache/watcher.(*BackendWatcher).Run
	/app/watcher/types.go:47 +0x3f
```

**Comment by martin-helmich** [comment]
Only occurs on initial startup -- seems fine for now.
